### ISSUE TITLE
Reset Password and other login messages suppressed when Clef plugin is enabled

### ISSUE THREAD

**Issue by labbeer** [clef/clef-wordpress#203]
With the Clef plugin enabled, messages displayed above the Wordpress login panel are being suppressed. Normally, they look like this:

![image](https://cloud.githubusercontent.com/assets/6623136/7289112/7d8beba2-e939-11e4-8c34-d93f5101dc1e.png)

These messages are particularly helpful with the WordPress password reset procedures, where tips like "Enter your new password below" and "Check email for the confirmation link" are displayed after a user takes actions in the panel. Unfortunately, these messages are suppressed when the Clef plugin is enabled. I tracked this down to a problem with the way the login_message filters are implemented, specifically in the `validate_invite` method of the ClefLogin class (defined in file class.clef-login.php). Here's where the Clef code in that file attempts to insert a custom login message:

`add_filter('login_message', array($this, 'validate_invite'));`

This `validate_invite` method does not account for existing messages that should still be displayed if invite validation succeeds. Here's the present code:

    public function validate_invite() {
        $invite_code = ClefUtils::isset_GET('clef_invite_code');
        $invite_email = base64_decode(ClefUtils::isset_GET('clef_invite_id'));
        $error = $this->validate_invite_code($invite_code, $invite_email);
        if ($invite_code && $error) {
            return '<div id="login_error">' . $error . '</div>';
        }
    }

In the function above, a message is returned if there's an error – but otherwise nothing else is returned, and any existing messages set via other `add_filter` calls are lost.

The above code should include a single parameter and return the existing message if no validation error occurs. Here's the WordPress Codex on usage of the login_message filter: https://codex.wordpress.org/Plugin_API/Filter_Reference/login_message

With a modification as follows, the default messages are back, and Clef can still generate its own message if invite code validation fails:

    public function validate_invite( $message ) {
        $invite_code = ClefUtils::isset_GET('clef_invite_code');
        $invite_email = base64_decode(ClefUtils::isset_GET('clef_invite_id'));
        $error = $this->validate_invite_code($invite_code, $invite_email);
        if ($invite_code && $error) {
            return '<div id="login_error">' . $error . '</div>';
        } 
        else { 
            return $message; 
        }
    } 

@jessepollak, take a look - and keep up the nice work on Clef!

**Comment by jessepollak** [comment]
Thanks for the detailed report, much appreciated! This fix will go out in 2.2.9.3 shortly :)
