### ISSUE TITLE
Disabling password access for users is also blocking wpengine from administering sites

### ISSUE THREAD

**Issue by sandiehughes** [clef/clef-wordpress#205]
Background: 
wpengine have an administrator user in each install, which currently means they're denied access on any sites I activate Clef on. Assuming that they also try to use this access for some of the automated maintenance they carry out on sites, this may explain some of the issues I've been experiencing on their hosting for the last few months. 

Request: 
A method of allowing my host to access the site without requiring them to use Clef, because realistically I'm just one customer and whilst I'd like them to use it, I can't insist. To expand this a little, it might be helpful to consider making this more generic than my request, and supplying an exclusion method for individuals within roles that for whatever reason won't be using Clef. As exclusions aren't ideal, perhaps they should be a configuration option that is outside of the plugin menu option, e.g. something in the functions or wpconfig files.

**Comment by JoeTheHuman** [comment]
Assuming that wpengine uses the API to fetch & execute things on our wordpress site, on the Clef settings page, you can enable login to the API

**Comment by sandiehughes** [comment]
The API option was enabled for the specific site I was dealing with when I raised this item. I'll ask wpengine to clarify their access method(s) so we might progress or dismiss this issue.

**Comment by lolux** [comment]
Hey @sandiehughes, I just wanted to follow up on this. A few weeks ago I assisted a Clef user who is using WPEngine for hosting, and having passwords disabled on the site did not block WPEngine support from accessing the site, performing maintenance, etc. Are you seeing something different?

**Comment by sandiehughes** [comment]
I don't have sufficient evidence that this is a problem to keep this issue open. I'm now suspecting Clef was just the fall guy for an issue that hasn't been fully pinned down. Happy for this issue to be closed.
