### ISSUE TITLE
CAUTION: Clef Wave May Cause CPU Burnout

### ISSUE THREAD

**Issue by JasonAlanKennedy** [clef/clef-wordpress#208]
Hi, I discovered If a user logs out and leaves the browser tab open (and active), the Clef Wave ramps the CPU to ~91% until he/she logs back in.

A team member today discovered that their laptop got extremely hot after a few minutes with the login screen left open. We checked the CPU usage in task manager when the WordPress login was left open and the tab active. If the Clef Wave is set as the default "primary login option", the CPU runs between 89% and 94% and when switching tabs (or close the wp login), the CPU will drop to a reasonable rate.

It may be a good idea to implement a redirect sending the user to the home page after logging out and/or add a function to switch from the Clef Wave to the "Log in with your phone" after a timeout interval (or something to that effect). Over the weekend, I personally lost a Chromebook - Apparently the CPU burnt up! After the fact of discovering today's indecent, I remembered on Friday, I logged out of WP and left the tab open. So most likely this was the cause of my Chromebook getting fried. I am concerned that this could become a serious liability if more machines are reported being damaged due to excessive CPU utilization over an extended period of time with this scenario.

Also, on a non-related note: Possibly move the plugin entry point from the upper-level Admin Menu to the Tools sub-menu using the  `add_options_page`.  This plugin is more of a "Set one time and forget about it."  This would follow WP's best practices by not cluttering up the Admin Panel with "settings-type" menus.

Thank-you very much

-j

**Comment by jessepollak** [comment]
Thanks for the heads up on this, we're looking into this issue!
