### ISSUE TITLE
Clef discontinuing

### ISSUE THREAD

**Issue by petrk94** [clef/clef-wordpress#263]
Hey
After Clef is stopping the development:
https://wordpress.org/support/topic/clef-is-shutting-down-by-june-6th-2017/
https://blog.getclef.com/discontinuing-support-for-clef-6c89febef5f3

Is there any open source plan?
I just heard about it and seems to be really great, what went wrong?
I really hope that it can developed continue as open source :(

**Comment by lolux** [comment]
Hi @petrk94, thanks for your enthusiasm for passwordless login. 

Another company is working on an open source replacement project: https://updraftplus.com/clef-user-updraftplus-now-gearing-replace/ and https://updraftplus.com/keyy-revealed-brand-name-clef-replacement-plugin/

**Comment by petrk94** [comment]
@lolux so the Clef repository will be closed or be the base of the replacements?
